project:
  type: website
  output-dir: docs

website:
  title: "assignment-3-meb448"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - M for Marvelous.qmd
      - M for Mara.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



